# Default easyos bootloader
APPLICATION = easyosboot_serial

# Include easyosboot flash partition functionality
# USEMODULE += easyosboot_slot

# Include serial bootloader functionality
USEMODULE += easyosboot_serial

include ../easyosboot_common.mk
